[package]
name = "almetica"
version = "0.0.1"
authors = ["Almetica <almetica@protonmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"

[dev-dependencies]
criterion = "0.3"
hex = "0.4.2"

[[bench]]
name = "crypt"
harness = false
