[package]
name = "almetica"
version = "0.0.1"
authors = ["Almetica <almetica@protonmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
byteorder = "1.3.4"
clap = { version = "3.0.0-beta.1", features = ["yaml"], git = "https://github.com/clap-rs/clap/" }
hex = "0.4.2"
log = "0.4"
pretty_env_logger = "0.4.0"
rand = "0.7.3"
rand_core = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1.0"
ucs2 = "0.3.1"

[dev-dependencies]
criterion = "0.3"
criterion-cycles-per-byte = "0.1.1"

[[bench]]
name = "crypt"
harness = false
