[package]
name = "almetica"
version = "0.0.1"
authors = ["Almetica <almetica@protonmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
clap = { version = "3.0.0-beta.1", features = ["yaml"], git = "https://github.com/clap-rs/clap/" }
hex = "0.4"
legion = { git = "https://github.com/TomGillen/legion/", branch = "master" }
rand = "0.7"
rand_core = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_yaml = "0.8"
strum = "0.18"
strum_macros = "0.18"
thiserror = "1.0"
tokio = { version = "0.2", features = ["blocking", "io-util", "macros", "net", "rt-threaded", "sync", "tcp"] }
tracing = { version ="0.1", features = ["max_level_trace", "release_max_level_info"]}
tracing-subscriber = "0.2"
tracing-futures = "0.2"
ucs2 = "0.3"
warp = "0.2"

[dev-dependencies]
criterion = "0.3"
criterion-cycles-per-byte = "0.1"
tokio = { version = "0.2", features = ["full"] }

[[bench]]
name = "crypt"
harness = false
